#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Sample.Resource", IsApplication=true)]

namespace Sample
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::ShapeLoadingViewCSharp.Resource.Attribute.loadingText = global::Sample.Resource.Attribute.loadingText;
			global::ShapeLoadingViewCSharp.Resource.Color.circle = global::Sample.Resource.Color.circle;
			global::ShapeLoadingViewCSharp.Resource.Color.rect = global::Sample.Resource.Color.rect;
			global::ShapeLoadingViewCSharp.Resource.Color.shadow = global::Sample.Resource.Color.shadow;
			global::ShapeLoadingViewCSharp.Resource.Color.triangle = global::Sample.Resource.Color.triangle;
			global::ShapeLoadingViewCSharp.Resource.Color.view_bg = global::Sample.Resource.Color.view_bg;
			global::ShapeLoadingViewCSharp.Resource.Drawable.Shadow = global::Sample.Resource.Drawable.Shadow;
			global::ShapeLoadingViewCSharp.Resource.Id.indication = global::Sample.Resource.Id.indication;
			global::ShapeLoadingViewCSharp.Resource.Id.promptTV = global::Sample.Resource.Id.promptTV;
			global::ShapeLoadingViewCSharp.Resource.Id.shapeLoadingView = global::Sample.Resource.Id.shapeLoadingView;
			global::ShapeLoadingViewCSharp.Resource.Layout.LoadView = global::Sample.Resource.Layout.LoadView;
			global::ShapeLoadingViewCSharp.Resource.String.ApplicationName = global::Sample.Resource.String.ApplicationName;
			global::ShapeLoadingViewCSharp.Resource.String.Hello = global::Sample.Resource.String.Hello;
			global::ShapeLoadingViewCSharp.Resource.Styleable.LoadingView = global::Sample.Resource.Styleable.LoadingView;
			global::ShapeLoadingViewCSharp.Resource.Styleable.LoadingView_loadingText = global::Sample.Resource.Styleable.LoadingView_loadingText;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int loadingText = 2130771968;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040001
			public const int circle = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int rect = 2130968578;
			
			// aapt resource value: 0x7f040004
			public const int shadow = 2130968580;
			
			// aapt resource value: 0x7f040000
			public const int triangle = 2130968576;
			
			// aapt resource value: 0x7f040003
			public const int view_bg = 2130968579;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Shadow = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060000
			public const int indication = 2131099648;
			
			// aapt resource value: 0x7f060003
			public const int loadView = 2131099651;
			
			// aapt resource value: 0x7f060001
			public const int promptTV = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int shapeLoadingView = 2131099650;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int LoadView = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] LoadingView = new int[] {
					2130771968};
			
			// aapt resource value: 0
			public const int LoadingView_loadingText = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
